#! /usr/bin/env python
#
# Support module generated by PAGE version 4.8.9
# In conjunction with Tcl version 8.6
#    Apr 03, 2017 05:44:29 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def ClearChat():
    print('chatwindow_support.ClearChat')
    sys.stdout.flush()

def ConnectToServer():
    print('chatwindow_support.ConnectToServer')
    sys.stdout.flush()

def DisplayInfo():
    print('chatwindow_support.DisplayInfo')
    sys.stdout.flush()

def Exit():
    print('chatwindow_support.Exit')
    sys.stdout.flush()

def SendMessage():
    print('chatwindow_support.SendMessage')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, chat_root
    w = gui
    top_level = top
    chat_root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import chatwindow
    chatwindow.vp_start_chat_gui()
