#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.8.9
# In conjunction with Tcl version 8.6
#    Mar 31, 2017 04:06:38 PM

import time
import sys
import os
import poker_ref 
from pygame import mixer
from random import randint
	
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import holdem_main_support
import chatwindow_support

root=Tk()

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    #Done in here to prevent 
    poker_ref.setInitialCardFileNames()		
	
    global val, w, root
    #root = Tk()
    root.resizable(0,0)
    top = New_Toplevel_1 (root)
    holdem_main_support.init(root, top)
    root.mainloop()

def playCardFlip():
    mixer.init()
    filename = ["./audio/cardPlace1.wav", "./audio/cardPlace2.wav", "./audio/cardPlace3.wav", "./audio/cardPlace4.wav"]
    sound = mixer.Sound(filename[randint(0,3)])
    mixer.Sound.play(sound)    
 
global messages
messages=""
def ChatReceive(message):
    global messages
    messages += message + "\n"
    #print(messages)
    #print("Received: "+message)
    top = New_Toplevel_1
    top.ChatUpdate(root, messages)
    
def updateGUI(image_update):
    top = New_Toplevel_1
    
    if ( image_update == "P1"):
        top.Player1(root)
    elif( image_update == "P2" ):
        top.Player2(root)
    elif( image_update == "P3" ):
        top.Player3(root)
    elif( image_update == "P4" ):
        top.Player4(root)
    elif( image_update == "P5" ):
        top.Player5(root)
    elif( image_update == "P6" ):
        top.Player6(root)
    elif( image_update == "P7" ):
        top.Player7(root)        
    elif( image_update == "P8" ):
        top.Player8(root)        
    elif( image_update == "F1" ):
        top.Flop1(root)
    elif( image_update == "F2" ):
        top.Flop2(root)
    elif( image_update == "F3" ):
        top.Flop3(root)
    elif( image_update == "F4" ):
        top.Flop4(root)
    elif( image_update == "F5" ):   
        top.Flop5(root)
    elif( image_update == "GAME_MSG"):
        top.WinMessage(root)
    else:
        top.refreshView(root)

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
    holdem_main_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def func(self, event):
        #print("You hit return.")
        self.ChatSend(self.ChatEntry.get())
     
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        print("Initializing GUI")
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("800x600+800+600")
        top.title("Texas Hold Em")
        top.configure(background="#1f3d1b")

        self.image = PhotoImage(file="./DECK/background.png")
        label = ttk.Label(top,image=self.image)
        label.place(x=0, y=0, relwidth=1.0, relheight=0.75, anchor="nw")

        time.sleep(0.5)
        self.refreshView()

        #self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        #top.configure(menu = self.menubar)


        #Begin game (Can only start when 2 players on server)
        self.Button1 = Button(top)
        self.Button1.place(relx=0.30, rely=0.65, height=30, width=72)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=self.playerCall) 
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Call''')
        
        self.Button1 = Button(top)
        self.Button1.place(relx=0.40, rely=0.65, height=30, width=72)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=self.playerRaise) 
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Raise''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.50, rely=0.65, height=30, width=72)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=self.playerCheck)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Check''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.60, rely=0.65, height=30, width=72)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=self.placeBet)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Bet''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.70, rely=0.65, height=30, width=72)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=self.playerFold)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Fold''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.08, rely=0.275, height=20, width=70)
        self.Label1.configure(background="#1b3917")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#FFF")
        self.Label1.configure(text='''Player 1''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.83, rely=0.275, height=20, width=70)
        self.Label1.configure(background="#1b3917")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#FFF")
        self.Label1.configure(text='''Player 2''')
        
        ###
        self.Label1 = Label(top)
        self.Label1.place(relx=0.05, rely=0.575, height=20, width=70)
        self.Label1.configure(background="#1b3917")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#FFF")
        self.Label1.configure(text='''Player 3''')
        
        self.Label1 = Label(top)
        self.Label1.place(relx=0.25, rely=0.575, height=20, width=70)
        self.Label1.configure(background="#1b3917")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#FFF")
        self.Label1.configure(text='''Player 4''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.40, rely=0.575, height=20, width=70)
        self.Label1.configure(background="#1b3917")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#FFF")
        self.Label1.configure(text='''Player 5''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.55, rely=0.575, height=20, width=70)
        self.Label1.configure(background="#1b3917")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#FFF")
        self.Label1.configure(text='''Player 6''')
        
        self.Label1 = Label(top)
        self.Label1.place(relx=0.70, rely=0.575, height=20, width=70)
        self.Label1.configure(background="#1b3917")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#FFF")
        self.Label1.configure(text='''Player 7''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.85, rely=0.575, height=20, width=70)
        self.Label1.configure(background="#1b3917")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#FFF")
        self.Label1.configure(text='''Player 8''')   

        ##BEGIN CHAT
        self.ChatWindow = ScrolledText(top)
        self.ChatWindow.place(relx=0.01, rely=0.775, relheight=0.15
                , relwidth=0.98)
        self.ChatWindow.configure(background="white")
        self.ChatWindow.configure(font="TkTextFont")
        self.ChatWindow.configure(insertborderwidth="3")
        self.ChatWindow.configure(selectbackground="#c4c4c4")
        self.ChatWindow.configure(undo="0")
        self.ChatWindow.configure(width=10)
        self.ChatWindow.configure(wrap=WORD)
        self.ChatWindow.configure(state='disabled')

        chat_send = StringVar()
        self.ChatEntry = ttk.Entry(top, textvariable = chat_send)
        self.ChatEntry.place(relx=0.01, rely=.94, relheight=0.05, relwidth=0.74)

        self.ChatEntry.configure(width=334)
        self.ChatEntry.configure(takefocus="")
        self.ChatEntry.configure(cursor="xterm")
        self.ChatEntry.bind('<Return>', self.func)
        
        self.SendButton = ttk.Button(top)
        self.SendButton.place(relx=0.76, rely=.94, height=25, width=100)
        
        self.SendButton.configure(command=lambda: self.ChatSend(chat_send.get()))
        self.SendButton.configure(takefocus="")
        self.SendButton.configure(text='''Send''')
        self.SendButton.configure(width=53)
        
        self.ExitButton = ttk.Button(top)
        self.ExitButton.place(relx=0.89, rely=.94, height=25, width=75)
        self.ExitButton.configure(command=self.Exit)
        self.ExitButton.configure(takefocus="")
        self.ExitButton.configure(text='''Exit''')
        self.ExitButton.configure(width=43)
        
    def playerReady(self):
        print("Player is ready!")
        
    def ClearChatBox(self):
        self.ChatWindow.delete(0,END)
        
    def Exit(self):
        os._exit(0)
        
    def ChatSend(self,message):
        poker_ref.outgoing(message)
        self.ChatEntry.delete(0,END)
        self.ChatWindow.see("end")

    def ChatUpdate(self,message):
        top=None
        self.ChatWindow = ScrolledText(top)
        self.ChatWindow.place(relx=0.01, rely=0.775, relheight=0.15
                , relwidth=0.98)
        self.ChatWindow.configure(background="white")
        self.ChatWindow.configure(font="TkTextFont")
        self.ChatWindow.configure(insertborderwidth="3")
        self.ChatWindow.configure(selectbackground="#c4c4c4")
        self.ChatWindow.configure(undo="0")
        self.ChatWindow.configure(width=10)
        self.ChatWindow.configure(wrap=WORD)
        self.ChatWindow.configure(state='normal')
        self.ChatWindow.insert(END, message)
        self.ChatWindow.configure(state='disabled')
        self.ChatWindow.see("end")
    def playerCall(self):
        poker_ref.playerCall()
        self.refreshView()
    def playerRaise(self):
        poker_ref.playerRaise()
        self.refreshView()
    def playerCheck(self):
        poker_ref.playerCheck()
        self.refreshView()
    def playerFold(self):
        poker_ref.playerFold()
        self.refreshView()
    def placeBet(self):
        poker_ref.placeBet()
        self.refreshView()
    def establishConnection(self):
        poker_ref.establishConnection()
        self.refreshView()
    def beginGame(self):
        poker_ref.test()
        self.refreshView()
        
    def refreshView(self):
         #Will check for 2+ players present
        top=None
        self.Player1Card1 = ttk.Label(top)
        self.Player1Card1.place(relx=0.04, rely=0.05, height=95, width=67)
        self.Player1Card1.configure(background="#000")
        self.Player1Card1.configure(foreground="#000000")
        self.Player1Card1.configure(relief=FLAT)
        self.Player1Card1.configure(text='''Tlabel''')
        self._img1 = PhotoImage(file=poker_ref.P1_Card1)
        self._img1 = self._img1.zoom(20)
        self._img1 = self._img1.subsample(32)
        self.Player1Card1.configure(image=self._img1)

        self.Player1Card2 = ttk.Label(top)
        self.Player1Card2.place(relx=0.08, rely=0.10, height=95, width=67)
        self.Player1Card2.configure(background="#000")
        self.Player1Card2.configure(foreground="#000000")
        self.Player1Card2.configure(relief=FLAT)
        self.Player1Card2.configure(text='''Tlabel''')
        self.Player1Card2.configure(width=104)
        self._img2 = PhotoImage(file=poker_ref.P1_Card2)
        self._img2 = self._img2.zoom(20)
        self._img2 = self._img2.subsample(32)
        self.Player1Card2.configure(image=self._img2)

        self.Player2Card1 = ttk.Label(top)
        self.Player2Card1.place(relx=0.88, rely=0.05, height=95, width=67)
        self.Player2Card1.configure(background="#000")
        self.Player2Card1.configure(foreground="#000000")
        self.Player2Card1.configure(relief=FLAT)
        self.Player2Card1.configure(text='''Tlabel''')
        self._img3 = PhotoImage(file=poker_ref.P2_Card1)
        self._img3 = self._img3.zoom(20)
        self._img3 = self._img3.subsample(32)
        self.Player2Card1.configure(image=self._img3)

        self.Player2Card2 = ttk.Label(top)
        self.Player2Card2.place(relx=0.83, rely=0.10, height=95, width=67)
        self.Player2Card2.configure(background="#000")
        self.Player2Card2.configure(foreground="#000000")
        self.Player2Card2.configure(relief=FLAT)
        self.Player2Card2.configure(text='''Tlabel''')
        self._img4 = PhotoImage(file=poker_ref.P2_Card2)
        self._img4 = self._img4.zoom(20)
        self._img4 = self._img4.subsample(32)
        self.Player2Card2.configure(image=self._img4)


        #"./DECK/deck_back.png" -- Default image
        self.Flop1 = ttk.Label(top)
        self.Flop1.place(relx=0.25, rely=0.05, height=95, width=67)
        self.Flop1.configure(background="#000")
        self.Flop1.configure(foreground="#000000")
        self.Flop1.configure(relief=FLAT)
        self.Flop1.configure(text='''Tlabel''')
        self.Flop1.configure(width=104)
        self._img5 = PhotoImage(file=poker_ref.Flop_Card1)
        self._img5 = self._img5.zoom(20)
        self._img5 = self._img5.subsample(32)
        self.Flop1.configure(image=self._img5)

        self.Flop2 = ttk.Label(top)
        self.Flop2.place(relx=0.35, rely=0.05, height=95, width=67)
        self.Flop2.configure(background="#000")
        self.Flop2.configure(foreground="#000000")
        self.Flop2.configure(relief=FLAT)
        self.Flop2.configure(text='''Tlabel''')
        self._img6 = PhotoImage(file=poker_ref.Flop_Card2)
        self._img6 = self._img6.zoom(20)
        self._img6 = self._img6.subsample(32)
        self.Flop2.configure(image=self._img6)

        self.Flop3 = ttk.Label(top)
        self.Flop3.place(relx=0.45, rely=0.05, height=95, width=67)
        self.Flop3.configure(background="#000")
        self.Flop3.configure(foreground="#000000")
        self.Flop3.configure(relief=FLAT)
        self.Flop3.configure(text='''Tlabel''')
        self.Flop3.configure(width=104)
        self._img7 = PhotoImage(file=poker_ref.Flop_Card3)
        self._img7 = self._img7.zoom(20)
        self._img7 = self._img7.subsample(32)
        self.Flop3.configure(image=self._img7)

        self.Flop4 = ttk.Label(top)
        self.Flop4.place(relx=0.55, rely=0.05, height=95, width=67)
        self.Flop4.configure(background="#000")
        self.Flop4.configure(foreground="#000000")
        self.Flop4.configure(relief=FLAT)
        self.Flop4.configure(text='''Tlabel''')
        self.Flop4.configure(width=104)
        self._img8 = PhotoImage(file=poker_ref.Flop_Card4)
        self._img8 = self._img8.zoom(20)
        self._img8 = self._img8.subsample(32)
        self.Flop4.configure(image=self._img8)

        self.Flop5 = ttk.Label(top)
        self.Flop5.place(relx=0.65, rely=0.05, height=95, width=67)
        self.Flop5.configure(background="#000")
        self.Flop5.configure(foreground="#000000")
        self.Flop5.configure(relief=FLAT)
        self.Flop5.configure(text='''Tlabel''')
        self.Flop5.configure(width=104)
        self._img9 = PhotoImage(file=poker_ref.Flop_Card5)
        self._img9 = self._img9.zoom(20)
        self._img9 = self._img9.subsample(32)
        self.Flop5.configure(image=self._img9)
        
        
        ##BEGIN PLAYER 3-9 CARDS
        
        
        self.Player3Card1 = ttk.Label(top)
        self.Player3Card1.place(relx=0.04, rely=0.35, height=95, width=67)
        self.Player3Card1.configure(background="#000")
        self.Player3Card1.configure(foreground="#000000")
        self.Player3Card1.configure(relief=FLAT)
        self.Player3Card1.configure(text='''Tlabel''')
        self.Player3Card1.configure(width=104)
        self._img10 = PhotoImage(file=poker_ref.P3_Card1)
        self._img10 = self._img10.zoom(20)
        self._img10 = self._img10.subsample(32)
        self.Player3Card1.configure(image=self._img10)
        
        self.Player3Card2 = ttk.Label(top)
        self.Player3Card2.place(relx=0.08, rely=0.40, height=95, width=67)
        self.Player3Card2.configure(background="#000")
        self.Player3Card2.configure(foreground="#000000")
        self.Player3Card2.configure(relief=FLAT)
        self.Player3Card2.configure(text='''Tlabel''')
        self.Player3Card2.configure(width=104)
        self._img11 = PhotoImage(file=poker_ref.P3_Card2)
        self._img11 = self._img11.zoom(20)
        self._img11 = self._img11.subsample(32)
        self.Player3Card2.configure(image=self._img11)

        self.Player4Card1 = ttk.Label(top)
        self.Player4Card1.place(relx=0.20, rely=0.35, height=95, width=67)
        self.Player4Card1.configure(background="#000")
        self.Player4Card1.configure(foreground="#000000")
        self.Player4Card1.configure(relief=FLAT)
        self.Player4Card1.configure(text='''Tlabel''')
        self._img12 = PhotoImage(file=poker_ref.P4_Card1)
        self._img12 = self._img12.zoom(20)
        self._img12 = self._img12.subsample(32)
        self.Player4Card1.configure(image=self._img12)
        
        self.Player4Card2 = ttk.Label(top)
        self.Player4Card2.place(relx=0.25, rely=0.40, height=95, width=67)
        self.Player4Card2.configure(background="#000")
        self.Player4Card2.configure(foreground="#000000")
        self.Player4Card2.configure(relief=FLAT)
        self.Player4Card2.configure(text='''Tlabel''')
        self._img13 = PhotoImage(file=poker_ref.P4_Card2)
        self._img13 = self._img13.zoom(20)
        self._img13 = self._img13.subsample(32)
        self.Player4Card2.configure(image=self._img13)        

        self.Player5Card1 = ttk.Label(top)
        self.Player5Card1.place(relx=0.35, rely=0.35, height=95, width=67)
        self.Player5Card1.configure(background="#000")
        self.Player5Card1.configure(foreground="#000000")
        self.Player5Card1.configure(relief=FLAT)
        self.Player5Card1.configure(text='''Tlabel''')
        self.Player5Card1.configure(width=104)
        self._img14 = PhotoImage(file=poker_ref.P5_Card1)
        self._img14 = self._img14.zoom(20)
        self._img14 = self._img14.subsample(32)
        self.Player5Card1.configure(image=self._img14)

        self.Player5Card2 = ttk.Label(top)
        self.Player5Card2.place(relx=0.40, rely=0.40, height=95, width=67)
        self.Player5Card2.configure(background="#000")
        self.Player5Card2.configure(foreground="#000000")
        self.Player5Card2.configure(relief=FLAT)
        self.Player5Card2.configure(text='''Tlabel''')
        self.Player5Card2.configure(width=104)
        self._img15 = PhotoImage(file=poker_ref.P5_Card2)
        self._img15 = self._img15.zoom(20)
        self._img15 = self._img15.subsample(32)
        self.Player5Card2.configure(image=self._img15)        
        
        self.Player6Card1 = ttk.Label(top)
        self.Player6Card1.place(relx=0.50, rely=0.35, height=95, width=67)
        self.Player6Card1.configure(background="#000")
        self.Player6Card1.configure(foreground="#000000")
        self.Player6Card1.configure(relief=FLAT)
        self.Player6Card1.configure(text='''Tlabel''')
        self.Player6Card1.configure(width=104)
        self._img16 = PhotoImage(file=poker_ref.P6_Card1)
        self._img16 = self._img16.zoom(20)
        self._img16 = self._img16.subsample(32)
        self.Player6Card1.configure(image=self._img16)

        self.Player6Card2 = ttk.Label(top)
        self.Player6Card2.place(relx=0.55, rely=0.40, height=95, width=67)
        self.Player6Card2.configure(background="#000")
        self.Player6Card2.configure(foreground="#000000")
        self.Player6Card2.configure(relief=FLAT)
        self.Player6Card2.configure(text='''Tlabel''')
        self.Player6Card2.configure(width=104)
        self._img17 = PhotoImage(file=poker_ref.P6_Card2)
        self._img17 = self._img17.zoom(20)
        self._img17 = self._img17.subsample(32)
        self.Player6Card2.configure(image=self._img17)        

        self.Player7Card1 = ttk.Label(top)
        self.Player7Card1.place(relx=0.65, rely=0.35, height=95, width=67)
        self.Player7Card1.configure(background="#000")
        self.Player7Card1.configure(foreground="#000000")
        self.Player7Card1.configure(relief=FLAT)
        self.Player7Card1.configure(text='''Tlabel''')
        self.Player7Card1.configure(width=104)
        self._img18 = PhotoImage(file=poker_ref.P7_Card1)
        self._img18 = self._img18.zoom(20)
        self._img18 = self._img18.subsample(32)
        self.Player7Card1.configure(image=self._img18)        

        self.Player7Card2 = ttk.Label(top)
        self.Player7Card2.place(relx=0.70, rely=0.40, height=95, width=67)
        self.Player7Card2.configure(background="#000")
        self.Player7Card2.configure(foreground="#000000")
        self.Player7Card2.configure(relief=FLAT)
        self.Player7Card2.configure(text='''Tlabel''')
        self.Player7Card2.configure(width=104)
        self._img19 = PhotoImage(file=poker_ref.P7_Card2)
        self._img19 = self._img19.zoom(20)
        self._img19 = self._img19.subsample(32)
        self.Player7Card2.configure(image=self._img19)         
        
        self.Player8Card1 = ttk.Label(top)
        self.Player8Card1.place(relx=0.88, rely=0.35, height=95, width=67)
        self.Player8Card1.configure(background="#000")
        self.Player8Card1.configure(foreground="#000000")
        self.Player8Card1.configure(relief=FLAT)
        self.Player8Card1.configure(text='''Tlabel''')
        self.Player8Card1.configure(width=104)
        self._img20 = PhotoImage(file=poker_ref.P8_Card1)
        self._img20 = self._img20.zoom(20)
        self._img20 = self._img20.subsample(32)
        self.Player8Card1.configure(image=self._img20)        

        self.Player8Card2 = ttk.Label(top)
        self.Player8Card2.place(relx=0.83, rely=0.40, height=95, width=67)
        self.Player8Card2.configure(background="#000")
        self.Player8Card2.configure(foreground="#000000")
        self.Player8Card2.configure(relief=FLAT)
        self.Player8Card2.configure(text='''Tlabel''')
        self.Player8Card2.configure(width=104)
        self._img21 = PhotoImage(file=poker_ref.P8_Card2)
        self._img21 = self._img21.zoom(20)
        self._img21 = self._img21.subsample(32)
        self.Player8Card2.configure(image=self._img21)             
        ##END PLAYER 3-9 CARDS
        

        self.WinLabel = Label(top)
        self.WinLabel.place(relx=0.35, rely=0.25, height=20, width=250)
        self.WinLabel.configure(background="#30552a")
        self.WinLabel.configure(disabledforeground="#a3a3a3")
        self.WinLabel.configure(foreground="#FFF")
        self.WinLabel.configure(text=poker_ref.winMessage)
        
        if ( "No Game" in poker_ref.winMessage ):
            mixer.init()
            filename = "./audio/cardShuffle.wav"
            sound = mixer.Sound(filename)
            mixer.Sound.play(sound)        
            
    def WinMessage(self):
        top=None
        self.WinLabel = Label(top)
        self.WinLabel.place(relx=0.35, rely=0.25, height=20, width=250)
        self.WinLabel.configure(background="#30552a")
        self.WinLabel.configure(disabledforeground="#a3a3a3")
        self.WinLabel.configure(foreground="#FFF")
        self.WinLabel.configure(text=poker_ref.winMessage)   
        if ( "Wins" in poker_ref.winMessage ):
            mixer.init()
            filename = "./audio/win.wav"
            sound = mixer.Sound(filename)
            mixer.Sound.play(sound)            

    def Player1(self):    
        top=None    
        self.Player1Card1 = ttk.Label(top)
        self.Player1Card1.place(relx=0.04, rely=0.05, height=95, width=67)
        self.Player1Card1.configure(background="#000")
        self.Player1Card1.configure(foreground="#000000")
        self.Player1Card1.configure(relief=FLAT)
        self.Player1Card1.configure(text='''Tlabel''')
        self._img1 = PhotoImage(file=poker_ref.P1_Card1)
        self._img1 = self._img1.zoom(20)
        self._img1 = self._img1.subsample(32)
        self.Player1Card1.configure(image=self._img1)

        self.Player1Card2 = ttk.Label(top)
        self.Player1Card2.place(relx=0.08, rely=0.10, height=95, width=67)
        self.Player1Card2.configure(background="#000")
        self.Player1Card2.configure(foreground="#000000")
        self.Player1Card2.configure(relief=FLAT)
        self.Player1Card2.configure(text='''Tlabel''')
        self.Player1Card2.configure(width=104)
        self._img2 = PhotoImage(file=poker_ref.P1_Card2)
        self._img2 = self._img2.zoom(20)
        self._img2 = self._img2.subsample(32)
        self.Player1Card2.configure(image=self._img2)
        playCardFlip()

    def Player2(self):
        top=None    
        self.Player2Card1 = ttk.Label(top)
        self.Player2Card1.place(relx=0.88, rely=0.05, height=95, width=67)
        self.Player2Card1.configure(background="#000")
        self.Player2Card1.configure(foreground="#000000")
        self.Player2Card1.configure(relief=FLAT)
        self.Player2Card1.configure(text='''Tlabel''')
        self._img3 = PhotoImage(file=poker_ref.P2_Card1)
        self._img3 = self._img3.zoom(20)
        self._img3 = self._img3.subsample(32)
        self.Player2Card1.configure(image=self._img3)

        self.Player2Card2 = ttk.Label(top)
        self.Player2Card2.place(relx=0.83, rely=0.10, height=95, width=67)
        self.Player2Card2.configure(background="#000")
        self.Player2Card2.configure(foreground="#000000")
        self.Player2Card2.configure(relief=FLAT)
        self.Player2Card2.configure(text='''Tlabel''')
        self._img4 = PhotoImage(file=poker_ref.P2_Card2)
        self._img4 = self._img4.zoom(20)
        self._img4 = self._img4.subsample(32)
        self.Player2Card2.configure(image=self._img4)
        playCardFlip()   
    def Player3(self):
        top=None        
        self.Player3Card1 = ttk.Label(top)
        self.Player3Card1.place(relx=0.04, rely=0.35, height=95, width=67)
        self.Player3Card1.configure(background="#000")
        self.Player3Card1.configure(foreground="#000000")
        self.Player3Card1.configure(relief=FLAT)
        self.Player3Card1.configure(text='''Tlabel''')
        self.Player3Card1.configure(width=104)
        self._img10 = PhotoImage(file=poker_ref.P3_Card1)
        self._img10 = self._img10.zoom(20)
        self._img10 = self._img10.subsample(32)
        self.Player3Card1.configure(image=self._img10)
        
        self.Player3Card2 = ttk.Label(top)
        self.Player3Card2.place(relx=0.08, rely=0.40, height=95, width=67)
        self.Player3Card2.configure(background="#000")
        self.Player3Card2.configure(foreground="#000000")
        self.Player3Card2.configure(relief=FLAT)
        self.Player3Card2.configure(text='''Tlabel''')
        self.Player3Card2.configure(width=104)
        self._img11 = PhotoImage(file=poker_ref.P3_Card2)
        self._img11 = self._img11.zoom(20)
        self._img11 = self._img11.subsample(32)
        self.Player3Card2.configure(image=self._img11)
        playCardFlip()        
    def Player4(self):
        top=None
        self.Player4Card1 = ttk.Label(top)
        self.Player4Card1.place(relx=0.20, rely=0.35, height=95, width=67)
        self.Player4Card1.configure(background="#000")
        self.Player4Card1.configure(foreground="#000000")
        self.Player4Card1.configure(relief=FLAT)
        self.Player4Card1.configure(text='''Tlabel''')
        self._img12 = PhotoImage(file=poker_ref.P4_Card1)
        self._img12 = self._img12.zoom(20)
        self._img12 = self._img12.subsample(32)
        self.Player4Card1.configure(image=self._img12)
        
        self.Player4Card2 = ttk.Label(top)
        self.Player4Card2.place(relx=0.25, rely=0.40, height=95, width=67)
        self.Player4Card2.configure(background="#000")
        self.Player4Card2.configure(foreground="#000000")
        self.Player4Card2.configure(relief=FLAT)
        self.Player4Card2.configure(text='''Tlabel''')
        self._img13 = PhotoImage(file=poker_ref.P4_Card2)
        self._img13 = self._img13.zoom(20)
        self._img13 = self._img13.subsample(32)
        self.Player4Card2.configure(image=self._img13)  
        playCardFlip()        
    def Player5(self):
        top=None
        self.Player5Card1 = ttk.Label(top)
        self.Player5Card1.place(relx=0.35, rely=0.35, height=95, width=67)
        self.Player5Card1.configure(background="#000")
        self.Player5Card1.configure(foreground="#000000")
        self.Player5Card1.configure(relief=FLAT)
        self.Player5Card1.configure(text='''Tlabel''')
        self.Player5Card1.configure(width=104)
        self._img14 = PhotoImage(file=poker_ref.P5_Card1)
        self._img14 = self._img14.zoom(20)
        self._img14 = self._img14.subsample(32)
        self.Player5Card1.configure(image=self._img14)

        self.Player5Card2 = ttk.Label(top)
        self.Player5Card2.place(relx=0.40, rely=0.40, height=95, width=67)
        self.Player5Card2.configure(background="#000")
        self.Player5Card2.configure(foreground="#000000")
        self.Player5Card2.configure(relief=FLAT)
        self.Player5Card2.configure(text='''Tlabel''')
        self.Player5Card2.configure(width=104)
        self._img15 = PhotoImage(file=poker_ref.P5_Card2)
        self._img15 = self._img15.zoom(20)
        self._img15 = self._img15.subsample(32)
        self.Player5Card2.configure(image=self._img15)  
        playCardFlip()        
    def Player6(self):
        top=None        
        self.Player6Card1 = ttk.Label(top)
        self.Player6Card1.place(relx=0.50, rely=0.35, height=95, width=67)
        self.Player6Card1.configure(background="#000")
        self.Player6Card1.configure(foreground="#000000")
        self.Player6Card1.configure(relief=FLAT)
        self.Player6Card1.configure(text='''Tlabel''')
        self.Player6Card1.configure(width=104)
        self._img16 = PhotoImage(file=poker_ref.P6_Card1)
        self._img16 = self._img16.zoom(20)
        self._img16 = self._img16.subsample(32)
        self.Player6Card1.configure(image=self._img16)

        self.Player6Card2 = ttk.Label(top)
        self.Player6Card2.place(relx=0.55, rely=0.40, height=95, width=67)
        self.Player6Card2.configure(background="#000")
        self.Player6Card2.configure(foreground="#000000")
        self.Player6Card2.configure(relief=FLAT)
        self.Player6Card2.configure(text='''Tlabel''')
        self.Player6Card2.configure(width=104)
        self._img17 = PhotoImage(file=poker_ref.P6_Card2)
        self._img17 = self._img17.zoom(20)
        self._img17 = self._img17.subsample(32)
        self.Player6Card2.configure(image=self._img17)    
        playCardFlip()        
    def Player7(self):
        top=None
        self.Player7Card1 = ttk.Label(top)
        self.Player7Card1.place(relx=0.65, rely=0.35, height=95, width=67)
        self.Player7Card1.configure(background="#000")
        self.Player7Card1.configure(foreground="#000000")
        self.Player7Card1.configure(relief=FLAT)
        self.Player7Card1.configure(text='''Tlabel''')
        self.Player7Card1.configure(width=104)
        self._img18 = PhotoImage(file=poker_ref.P7_Card1)
        self._img18 = self._img18.zoom(20)
        self._img18 = self._img18.subsample(32)
        self.Player7Card1.configure(image=self._img18)        

        self.Player7Card2 = ttk.Label(top)
        self.Player7Card2.place(relx=0.70, rely=0.40, height=95, width=67)
        self.Player7Card2.configure(background="#000")
        self.Player7Card2.configure(foreground="#000000")
        self.Player7Card2.configure(relief=FLAT)
        self.Player7Card2.configure(text='''Tlabel''')
        self.Player7Card2.configure(width=104)
        self._img19 = PhotoImage(file=poker_ref.P7_Card2)
        self._img19 = self._img19.zoom(20)
        self._img19 = self._img19.subsample(32)
        self.Player7Card2.configure(image=self._img19)  
        playCardFlip()        
    def Player8(self):
        top=None        
        self.Player8Card1 = ttk.Label(top)
        self.Player8Card1.place(relx=0.88, rely=0.35, height=95, width=67)
        self.Player8Card1.configure(background="#000")
        self.Player8Card1.configure(foreground="#000000")
        self.Player8Card1.configure(relief=FLAT)
        self.Player8Card1.configure(text='''Tlabel''')
        self.Player8Card1.configure(width=104)
        self._img20 = PhotoImage(file=poker_ref.P8_Card1)
        self._img20 = self._img20.zoom(20)
        self._img20 = self._img20.subsample(32)
        self.Player8Card1.configure(image=self._img20)        

        self.Player8Card2 = ttk.Label(top)
        self.Player8Card2.place(relx=0.83, rely=0.40, height=95, width=67)
        self.Player8Card2.configure(background="#000")
        self.Player8Card2.configure(foreground="#000000")
        self.Player8Card2.configure(relief=FLAT)
        self.Player8Card2.configure(text='''Tlabel''')
        self.Player8Card2.configure(width=104)
        self._img21 = PhotoImage(file=poker_ref.P8_Card2)
        self._img21 = self._img21.zoom(20)
        self._img21 = self._img21.subsample(32)
        self.Player8Card2.configure(image=self._img21)           
        playCardFlip()        
    def Flop1(self):
        top=None    
        self.Flop1 = ttk.Label(top)
        self.Flop1.place(relx=0.25, rely=0.05, height=95, width=67)
        self.Flop1.configure(background="#000")
        self.Flop1.configure(foreground="#000000")
        self.Flop1.configure(relief=FLAT)
        self.Flop1.configure(text='''Tlabel''')
        self.Flop1.configure(width=104)
        self._img5 = PhotoImage(file=poker_ref.Flop_Card1)
        self._img5 = self._img5.zoom(20)
        self._img5 = self._img5.subsample(32)
        self.Flop1.configure(image=self._img5)
        playCardFlip()    
    
    def Flop2(self):
        top=None    
        self.Flop2 = ttk.Label(top)
        self.Flop2.place(relx=0.35, rely=0.05, height=95, width=67)
        self.Flop2.configure(background="#000")
        self.Flop2.configure(foreground="#000000")
        self.Flop2.configure(relief=FLAT)
        self.Flop2.configure(text='''Tlabel''')
        self._img6 = PhotoImage(file=poker_ref.Flop_Card2)
        self._img6 = self._img6.zoom(20)
        self._img6 = self._img6.subsample(32)
        self.Flop2.configure(image=self._img6)
        playCardFlip()    
    def Flop3(self):
        top=None    
        self.Flop3 = ttk.Label(top)
        self.Flop3.place(relx=0.45, rely=0.05, height=95, width=67)
        self.Flop3.configure(background="#000")
        self.Flop3.configure(foreground="#000000")
        self.Flop3.configure(relief=FLAT)
        self.Flop3.configure(text='''Tlabel''')
        self.Flop3.configure(width=104)
        self._img7 = PhotoImage(file=poker_ref.Flop_Card3)
        self._img7 = self._img7.zoom(20)
        self._img7 = self._img7.subsample(32)
        self.Flop3.configure(image=self._img7)
        playCardFlip()    

    def Flop4(self):
        top=None
        self.Flop4 = ttk.Label(top)
        self.Flop4.place(relx=0.55, rely=0.05, height=95, width=67)
        self.Flop4.configure(background="#000")
        self.Flop4.configure(foreground="#000000")
        self.Flop4.configure(relief=FLAT)
        self.Flop4.configure(text='''Tlabel''')
        self.Flop4.configure(width=104)
        self._img8 = PhotoImage(file=poker_ref.Flop_Card4)
        self._img8 = self._img8.zoom(20)
        self._img8 = self._img8.subsample(32)
        self.Flop4.configure(image=self._img8)
        playCardFlip()    
    def Flop5(self):
        top=None
        self.Flop5 = ttk.Label(top)
        self.Flop5.place(relx=0.65, rely=0.05, height=95, width=67)
        self.Flop5.configure(background="#000")
        self.Flop5.configure(foreground="#000000")
        self.Flop5.configure(relief=FLAT)
        self.Flop5.configure(text='''Tlabel''')
        self.Flop5.configure(width=104)
        self._img9 = PhotoImage(file=poker_ref.Flop_Card5)
        self._img9 = self._img9.zoom(20)
        self._img9 = self._img9.subsample(32)
        self.Flop5.configure(image=self._img9)
        playCardFlip()            


# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = Pack.__dict__.keys() | Grid.__dict__.keys() \
                  | Place.__dict__.keys()
        else:
            methods = Pack.__dict__.keys() + Grid.__dict__.keys() \
                  + Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)        
        
if __name__ == '__main__':
    vp_start_gui()
